polcode_user:
    resource: "@PolcodeUserBundle/Resources/config/routing.yml"
    prefix:   /

polcode_cms:
    resource: "@PolcodeCmsBundle/Resources/config/routing.yml"
    prefix:   /admin/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
